-- ============================================================
-- PeptideTracker — Peptide Library Seed Data (21+ peptides)
-- Run AFTER schema.sql AND add_peptide_info_columns.sql
-- ============================================================

INSERT INTO peptides (slug, name_es, name_en, description_es, description_en, routes, typical_dose_min, typical_dose_max, dose_unit, half_life_hours, reconstitution_notes_es, side_effects_es, tags)
ON CONFLICT (slug) DO NOTHING
VALUES

('bpc-157', 'BPC-157', 'BPC-157',
 'Péptido de cuerpo protector 157. Conocido por sus propiedades regenerativas y de recuperación. Muy utilizado para sanar tejidos, tendones, ligamentos y úlceras gástricas.',
 'Body Protection Compound 157. Known for regenerative and recovery properties.',
 ARRAY['subcutaneous','intramuscular','oral'], 200, 500, 'mcg', 4,
 'Disuelve en 1-2ml de agua bacteriostática. Estable 4 semanas en refrigeración.',
 'Náuseas leves, mareos ocasionales, sensación de calor. Generalmente bien tolerado.',
 ARRAY['recuperación','tejidos','GI','tendones']),

('tb-500', 'TB-500', 'TB-500',
 'Fragmento sintético de la Timosina Beta-4. Promueve la curación de heridas, reduce la inflamación y mejora la flexibilidad.',
 'Synthetic fragment of Thymosin Beta-4. Promotes wound healing and reduces inflammation.',
 ARRAY['subcutaneous','intramuscular'], 2000, 5000, 'mcg', 24,
 'Reconstituir en 1-2ml de agua bacteriostática. Estable hasta 4 semanas refrigerado.',
 'Fatiga temporal, mareos ligeros. Bien tolerado en general.',
 ARRAY['recuperación','inflamación','músculos','atletas']),

('semaglutide', 'Semaglutida', 'Semaglutide',
 'Agonista del receptor GLP-1 de acción prolongada. Usado para pérdida de peso y control glucémico. Reduce el apetito y la ingesta calórica.',
 'Long-acting GLP-1 receptor agonist used for weight loss and glycemic control.',
 ARRAY['subcutaneous'], 250, 2000, 'mcg', 168,
 'Reconstituir con agua bacteriostática. Cada mg da ~4 semanas de dosis semanales típicas. Conservar refrigerado.',
 'Náuseas, vómitos, diarrea (principalmente al inicio), estreñimiento, reflujo.',
 ARRAY['pérdida de peso','GLP-1','metabolismo','diabetes']),

('tirzepatide', 'Tirzepatida', 'Tirzepatide',
 'Agonista dual GIP/GLP-1 de acción prolongada. Mayor efectividad en pérdida de peso que semaglutida en estudios clínicos.',
 'Dual GIP/GLP-1 receptor agonist with superior weight loss efficacy.',
 ARRAY['subcutaneous'], 2500, 15000, 'mcg', 120,
 'Reconstituir con agua bacteriostática. Administración semanal. Escalar dosis lentamente.',
 'Náuseas, vómitos, diarrea, dolor abdominal, especialmente al inicio del protocolo.',
 ARRAY['pérdida de peso','GLP-1','GIP','metabolismo']),

('retatrutide', 'Retatrutida', 'Retatrutide',
 'Triple agonista GLP-1/GIP/Glucagón de acción prolongada (Eli Lilly). Produce la mayor pérdida de peso documentada entre todos los agentes de esta clase (~24% en ensayos Fase 3). Activa tres vías metabólicas simultáneamente.',
 'Triple GLP-1/GIP/Glucagon receptor agonist showing unprecedented ~24% weight loss in Phase 3 trials. Made by Eli Lilly.',
 ARRAY['subcutaneous'], 500, 12000, 'mcg', 168,
 'Reconstituir con agua bacteriostática si en polvo liofilizado. Administración semanal SC. Escalar muy lentamente.',
 'Náuseas (más frecuentes que semaglutida), vómitos, diarrea, dolor abdominal, saciedad extrema, estreñimiento.',
 ARRAY['pérdida de peso','GLP-1','GIP','glucagón','metabolismo','triple agonista']),

('cjc-1295', 'CJC-1295', 'CJC-1295',
 'Péptido liberador de hormona de crecimiento (GHRH) modificado con DAC para semivida prolongada. Estimula la liberación de GH de forma pulsátil.',
 'Modified GHRH analog with DAC for extended half-life. Stimulates pulsatile GH release.',
 ARRAY['subcutaneous'], 1000, 2000, 'mcg', 168,
 'Reconstituir en 2ml de agua bacteriostática. Estable 4 semanas refrigerado. Administrar 1-2x semana.',
 'Rubor facial, fatiga, retención leve de agua, picor en sitio de inyección.',
 ARRAY['HGH','GHRH','longevidad','composición corporal']),

('ipamorelin', 'Ipamorelin', 'Ipamorelin',
 'Secretagogo selectivo de GH con mínimo efecto sobre cortisol y prolactina. Muy usado en combinación con CJC-1295.',
 'Selective GH secretagogue with minimal effect on cortisol and prolactin.',
 ARRAY['subcutaneous'], 100, 300, 'mcg', 2,
 'Reconstituir en 2ml de agua bacteriostática. Estable 30 días refrigerado. Usar 2-3x diario.',
 'Rubor leve, ligero aumento de apetito, somnolencia frecuente.',
 ARRAY['HGH','GHRP','longevidad','sueño']),

('ghk-cu', 'GHK-Cu', 'GHK-Cu',
 'Péptido tripéptido de cobre que regula genes del ADN, estimula la producción de colágeno y tiene propiedades antienvejecimiento.',
 'Copper peptide that regulates DNA genes, stimulates collagen, and has anti-aging properties.',
 ARRAY['subcutaneous','topical'], 500, 1500, 'mcg', 4,
 'Reconstituir en 1-2ml de agua bacteriostática. Para uso tópico diluir más. Estable 4 semanas refrigerado.',
 'Enrojecimiento cutáneo leve (tópico), sabor metálico ocasional.',
 ARRAY['longevidad','piel','colágeno','antienvejecimiento']),

('sermorelin', 'Sermorelin', 'Sermorelin',
 'Análogo sintético del GHRH. Estimula la glándula pituitaria para producir y liberar GH de manera natural.',
 'Synthetic GHRH analog that stimulates the pituitary to produce GH naturally.',
 ARRAY['subcutaneous'], 200, 500, 'mcg', 0.17,
 'Reconstituir en 1ml de agua bacteriostática. Muy corta vida media, administrar antes de dormir.',
 'Rubor facial, mareos, somnolencia, dolor de cabeza transitorio.',
 ARRAY['HGH','GHRH','longevidad','sueño']),

('aod-9604', 'AOD-9604', 'AOD-9604',
 'Fragmento de la hormona de crecimiento humana (hGH176-191). Activa la quema de grasa sin los efectos secundarios del HGH completo.',
 'Fragment of human growth hormone specifically for fat burning without HGH side effects.',
 ARRAY['subcutaneous'], 300, 600, 'mcg', 3,
 'Reconstituir en 1-2ml de agua bacteriostática. Estable 4 semanas refrigerado. Administrar en ayunas.',
 'Bien tolerado. Ocasionalmente: rubor leve, picazón en sitio de inyección.',
 ARRAY['pérdida de grasa','lipólisis','HGH','metabolismo']),

('pt-141', 'PT-141 (Bremelanotida)', 'PT-141 (Bremelanotide)',
 'Agonista del receptor de melanocortina. Usado para disfunción sexual en hombres (DE) y mujeres (HSDD). Actúa sobre el SNC.',
 'Melanocortin receptor agonist for sexual dysfunction in both men and women.',
 ARRAY['subcutaneous','nasal'], 500, 2000, 'mcg', 12,
 'Reconstituir en 1-2ml de agua bacteriostática. Para uso nasal diluir en solución salina.',
 'Náuseas, rubor facial, aumento de presión arterial, dolor de cabeza, hiperpigmentación.',
 ARRAY['sexual','libido','melanocortina']),

('melanotan-ii', 'Melanotan II', 'Melanotan II',
 'Análogo de la hormona estimulante de melanocitos (α-MSH). Estimula la pigmentación de la piel sin exposición UV, aumenta libido.',
 'Melanocyte-stimulating hormone analog promoting tanning, libido, and appetite suppression.',
 ARRAY['subcutaneous'], 250, 1000, 'mcg', 24,
 'Reconstituir en 1-2ml de agua bacteriostática. Iniciar con dosis bajas y escalar.',
 'Náuseas, rubor, erecciones espontáneas, oscurecimiento de nevos existentes, fatiga.',
 ARRAY['bronceado','libido','melanocortina','apetito']),

('epithalon', 'Epitalon', 'Epithalon',
 'Tetrapéptido derivado del epitalamus. Activa la telomerasa, alargando los telómeros. Regula la melatonina y mejora patrones de sueño.',
 'Tetrapeptide that activates telomerase, elongates telomeres, and regulates melatonin.',
 ARRAY['subcutaneous','intramuscular'], 5000, 10000, 'mcg', 4,
 'Reconstituir en 1-2ml de agua bacteriostática. Protocolo típico: 10 días consecutivos 2x año.',
 'Generalmente bien tolerado. Posibles sueños vívidos, somnolencia.',
 ARRAY['longevidad','telómeros','sueño','antienvejecimiento']),

('ss-31', 'SS-31 (Elamipretida)', 'SS-31 (Elamipretide)',
 'Péptido mitocondrial que mejora la función mitocondrial. Estudios muestran mejoras en energía celular y función cardíaca.',
 'Mitochondria-targeted peptide that improves mitochondrial function and cellular energy.',
 ARRAY['subcutaneous'], 1000, 5000, 'mcg', 3,
 'Reconstituir en 1ml de agua bacteriostática. MUY inestable: usar dentro de 24h. Conservar en hielo.',
 'Reacciones locales en sitio de inyección, rubor transitorio.',
 ARRAY['mitocondrias','energía','longevidad','cardiovascular']),

('dsip', 'DSIP (Péptido Inductor del Sueño Delta)', 'DSIP (Delta Sleep Inducing Peptide)',
 'Neuropéptido que promueve el sueño delta profundo, regula el cortisol y la GH.',
 'Neuropeptide that promotes deep delta sleep and regulates cortisol and GH.',
 ARRAY['subcutaneous'], 100, 500, 'mcg', 0.5,
 'Reconstituir en 1ml de agua bacteriostática. Administrar 20-30 min antes de dormir. Estable 48h.',
 'Somnolencia (efecto deseado), náuseas leves, dolores de cabeza ocasionales.',
 ARRAY['sueño','cortisol','HGH','estrés']),

('selank', 'Selank', 'Selank',
 'Péptido ansiolítico y nootrópico de origen ruso. Derivado de la tuftosina. Reduce ansiedad sin sedación.',
 'Anxiolytic and nootropic peptide derived from tuftsin. Reduces anxiety without sedation.',
 ARRAY['nasal','subcutaneous'], 250, 3000, 'mcg', 2,
 'Para uso nasal: diluir en solución salina al 0.9%. Para SC: reconstituir en 1ml agua bacteriostática.',
 'Bien tolerado. Somnolencia leve, ligero aumento de apetito.',
 ARRAY['ansiedad','nootrópico','cognitivo','inmunidad']),

('semax', 'Semax', 'Semax',
 'Péptido nootrópico sintético derivado de ACTH. Mejora la memoria, concentración y estado de ánimo. Aumenta BDNF.',
 'Synthetic nootropic derived from ACTH. Improves memory, focus, and increases BDNF.',
 ARRAY['nasal','subcutaneous'], 100, 3000, 'mcg', 0.5,
 'Para uso nasal: diluir en solución salina. Para SC: reconstituir en 1ml agua bacteriostática.',
 'Generalmente bien tolerado. Posible irritación nasal, cefalea leve.',
 ARRAY['nootrópico','cognitivo','BDNF','memoria']),

('kpv', 'KPV', 'KPV',
 'Tripéptido antiinflamatorio derivado del extremo C-terminal del α-MSH. Especialmente efectivo en tracto gastrointestinal.',
 'Anti-inflammatory tripeptide derived from α-MSH C-terminal. Particularly effective for GI inflammation.',
 ARRAY['oral','subcutaneous'], 500, 5000, 'mcg', 2,
 'Para oral: disolver en agua. Para SC: reconstituir en 1ml agua bacteriostática.',
 'Bien tolerado. Rara vez: molestias digestivas leves.',
 ARRAY['inflamación','GI','intestinal','antiinflamatorio']),

('ll-37', 'LL-37', 'LL-37',
 'Péptido antimicrobiano catiónico, único miembro humano de la familia de catelicidinas. Amplio espectro antimicrobiano.',
 'Antimicrobial cathelicidin peptide with broad-spectrum antibacterial and immunomodulatory effects.',
 ARRAY['subcutaneous','topical'], 100, 500, 'mcg', 6,
 'Reconstituir en 1ml agua bacteriostática. Para tópico diluir en gel o crema. Estable 2 semanas.',
 'Dolor/rubor en sitio de inyección. Tópico: irritación cutánea posible.',
 ARRAY['antimicrobiano','inmunidad','cicatrización','infecciones']),

('hexarelin', 'Hexarelina', 'Hexarelin',
 'Péptido secretagogo de GH de la familia GHRP. Más potente que el GHRP-6. Tiene efectos cardioprotectores independientes de la GH.',
 'Potent GH secretagogue from GHRP family with additional cardioprotective effects.',
 ARRAY['subcutaneous'], 100, 200, 'mcg', 1,
 'Reconstituir en 2ml de agua bacteriostática. Administrar 2-3x diario en ayunas. Estable 30 días.',
 'Aumento de cortisol y prolactina, rubor, somnolencia, aumento de apetito significativo.',
 ARRAY['HGH','GHRP','cardíaco','composición corporal']),

('ghrp-6', 'GHRP-6', 'GHRP-6',
 'Péptido liberador de GH de la familia grelina. Estimula fuertemente el apetito además de la liberación de GH.',
 'Ghrelin-family GH-releasing peptide that strongly stimulates appetite and GH release.',
 ARRAY['subcutaneous'], 100, 300, 'mcg', 0.5,
 'Reconstituir en 2ml agua bacteriostática. Administrar 2-3x diario en ayunas. Estable 30 días.',
 'Aumento significativo de apetito (hambre inmediata), rubor, somnolencia, letargia.',
 ARRAY['HGH','GHRP','apetito','composición corporal']),

('bpc-157-nasal', 'BPC-157 Nasal', 'BPC-157 Nasal',
 'Formulación nasal del BPC-157. Mayor biodisponibilidad cerebral por vía intranasal para patologías del SNC.',
 'Nasal formulation of BPC-157 with enhanced brain bioavailability for CNS applications.',
 ARRAY['nasal'], 250, 500, 'mcg', 4,
 'Disolver en 5ml de solución salina al 0.9% para uso nasal. NO usar agua bacteriostática para vía nasal.',
 'Irritación nasal leve, congestión temporal.',
 ARRAY['cerebro','neuroprotección','BPC-157','SNC']);
